import type { FamilyTree, Person } from '@/types';
import {
  getDisplayName,
  formatDate,
  formatYear,
  getGeneration,
  getParents,
  getSpouses,
  getChildren,
} from '@/lib/treeUtils';

export interface ExportOptions {
  includePhotos: boolean;
  includeBios: boolean;
  includeTimeline: boolean;
  paperSize: 'A4' | 'A5' | 'Letter';
  theme: 'atelier' | 'classic' | 'minimal';
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Escape user-provided text before injecting it into the standalone HTML doc. */
function escapeHtml(input: string | undefined | null): string {
  if (!input) return '';
  return String(input)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

interface Palette {
  bg: string;
  ink: string;
  inkSoft: string;
  accent: string;
  cardBg: string;
  border: string;
  /** font-family stacks already containing fallbacks */
  display: string;
  body: string;
  /** fiche border CSS (full shorthand) */
  ficheBorder: string;
  ficheShadow: string;
  /** generation band rendering */
  bandBg: string;
  bandInk: string;
  separator: string;
}

const PALETTES: Record<ExportOptions['theme'], Palette> = {
  atelier: {
    bg: '#f4f1ea',
    ink: '#1b1b1b',
    inkSoft: '#4a4742',
    accent: '#bf4b2c',
    cardBg: '#ffffff',
    border: '#1b1b1b',
    display: "'Bricolage Grotesque', sans-serif",
    body: "'Hanken Grotesk', sans-serif",
    ficheBorder: '1.5px solid #1b1b1b',
    ficheShadow: '4px 4px 0 #1b1b1b',
    bandBg: '#1b1b1b',
    bandInk: '#f4f1ea',
    separator: '#bf4b2c',
  },
  classic: {
    bg: '#f6f1e7',
    ink: '#2a2620',
    inkSoft: '#5b5347',
    accent: '#7a5230',
    cardBg: '#fffdf8',
    border: '#c8b89a',
    display: "'Bricolage Grotesque', Georgia, serif",
    body: "'Hanken Grotesk', Georgia, serif",
    ficheBorder: '1px solid #c8b89a',
    ficheShadow: '0 2px 8px rgba(122, 82, 48, 0.12)',
    bandBg: '#7a5230',
    bandInk: '#fffdf8',
    separator: '#b89968',
  },
  minimal: {
    bg: '#ffffff',
    ink: '#111111',
    inkSoft: '#666666',
    accent: '#111111',
    cardBg: '#ffffff',
    border: '#e2e2e2',
    display: "'Hanken Grotesk', sans-serif",
    body: "'Hanken Grotesk', sans-serif",
    ficheBorder: '1px solid #e2e2e2',
    ficheShadow: 'none',
    bandBg: 'transparent',
    bandInk: '#111111',
    separator: '#dddddd',
  },
};

function pageMargin(size: ExportOptions['paperSize']): string {
  switch (size) {
    case 'A5':
      return '12mm';
    case 'Letter':
      return '18mm';
    case 'A4':
    default:
      return '18mm';
  }
}

const I18N = {
  fr: {
    cover: 'Livret de famille',
    family: 'Famille',
    subtitle: 'Arbre généalogique',
    generatedBy: 'Généré par Suimini',
    on: 'le',
    sommaireTitle: 'Présentation de la lignée',
    generations: 'générations',
    members: 'membres',
    fromTo: 'du plus ancien au plus récent',
    sommaire: 'Sommaire',
    generation: 'Génération',
    founders: 'Les fondateurs',
    bornOnM: 'né le',
    bornOnF: 'née le',
    bornOnN: 'né(e) le',
    in: 'à',
    diedM: 'décédé le',
    diedF: 'décédée le',
    diedN: 'décédé(e) le',
    occupation: 'Profession',
    biography: 'Biographie',
    parents: 'Parents',
    spouses: 'Époux/Épouse',
    children: 'Enfants',
    chronology: 'Chronologie',
    index: 'Index alphabétique',
    gen: 'gén.',
    noData: '—',
    docFooterConfidential: 'Document confidentiel — usage familial strictement',
  },
  en: {
    cover: 'Family booklet',
    family: 'Family',
    subtitle: 'Family tree',
    generatedBy: 'Generated by Suimini',
    on: 'on',
    sommaireTitle: 'About this lineage',
    generations: 'generations',
    members: 'members',
    fromTo: 'from the earliest to the most recent',
    sommaire: 'Contents',
    generation: 'Generation',
    founders: 'The founders',
    bornOnM: 'born on',
    bornOnF: 'born on',
    bornOnN: 'born on',
    in: 'in',
    diedM: 'died on',
    diedF: 'died on',
    diedN: 'died on',
    occupation: 'Occupation',
    biography: 'Biography',
    parents: 'Parents',
    spouses: 'Spouse',
    children: 'Children',
    chronology: 'Timeline',
    index: 'Alphabetical index',
    gen: 'gen.',
    noData: '—',
    docFooterConfidential: 'Confidential document — strictly for family use',
  },
};

type Strings = typeof I18N.fr;

function place(p?: { city?: string; country?: string }): string {
  if (!p) return '';
  return [p.city, p.country].filter(Boolean).join(', ');
}

function bornLabel(p: Person, s: Strings): string {
  return p.gender === 'male' ? s.bornOnM : p.gender === 'female' ? s.bornOnF : s.bornOnN;
}
function diedLabel(p: Person, s: Strings): string {
  return p.gender === 'male' ? s.diedM : p.gender === 'female' ? s.diedF : s.diedN;
}

/** Groups persons by generation depth (0-based), each sorted by name. */
function groupByGeneration(tree: FamilyTree): { gen: number; people: Person[] }[] {
  const memo = new Map<string, number>();
  const byGen = new Map<number, Person[]>();
  tree.persons.forEach((p) => {
    const g = getGeneration(p.id, tree.relationships, tree.persons, memo);
    const arr = byGen.get(g) ?? [];
    arr.push(p);
    byGen.set(g, arr);
  });
  return [...byGen.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([gen, people]) => ({
      gen,
      people: [...people].sort(
        (a, b) => a.lastName.localeCompare(b.lastName) || a.firstName.localeCompare(b.firstName),
      ),
    }));
}

/** Earliest birth year and latest birth/death year across the tree. */
function yearRange(tree: FamilyTree): { min?: number; max?: number } {
  const years: number[] = [];
  tree.persons.forEach((p) => {
    if (p.birthDate) years.push(new Date(p.birthDate).getFullYear());
    if (p.deathDate) years.push(new Date(p.deathDate).getFullYear());
  });
  if (years.length === 0) return {};
  return { min: Math.min(...years), max: Math.max(...years) };
}

// ---------------------------------------------------------------------------
// Page count estimate (cover + sommaire + per-generation pages + index)
// ---------------------------------------------------------------------------

export function estimatePageCount(tree: FamilyTree, options: ExportOptions): number {
  const groups = groupByGeneration(tree);
  // Fiches per page depends on how dense each fiche is.
  const perPage = options.includeBios || options.includePhotos ? 4 : 6;
  let genPages = 0;
  groups.forEach(({ people }) => {
    genPages += Math.max(1, Math.ceil(people.length / perPage));
  });
  const indexPages = Math.max(1, Math.ceil(tree.persons.length / 40));
  // cover (1) + sommaire (1) + generation pages + index
  return 2 + genPages + indexPages;
}

// ---------------------------------------------------------------------------
// Main HTML generator
// ---------------------------------------------------------------------------

export function generateFamilyBookHTML(
  tree: FamilyTree,
  options: ExportOptions,
  locale?: string,
): string {
  const lang = locale === 'en' ? 'en' : 'fr';
  const s = I18N[lang];
  const pal = PALETTES[options.theme];
  const dateLocale = lang === 'en' ? 'en-US' : 'fr-FR';
  const today = new Date().toLocaleDateString(dateLocale, {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });

  const groups = groupByGeneration(tree);
  const generationCount = groups.length;
  const memberCount = tree.persons.length;
  const range = yearRange(tree);
  const rangeLabel =
    range.min != null && range.max != null
      ? `${range.min} – ${range.max}`
      : range.min != null
        ? `${range.min}`
        : s.noData;

  // ---- Cover (page 1) -------------------------------------------------------
  // Avoid "FAMILLE FAMILLE DUPONT" when the tree name already starts with "Famille".
  const rawName = (tree.name || '').trim();
  const coverTitle = /^famille\b/i.test(rawName)
    ? rawName.toUpperCase()
    : `${s.family.toUpperCase()} ${rawName.toUpperCase()}`;
  const cover = `
    <section class="page cover">
      <div class="cover-inner">
        <div class="cover-eyebrow">${escapeHtml(s.cover)}</div>
        <h1 class="cover-title">${escapeHtml(coverTitle)}</h1>
        <div class="cover-sub">${escapeHtml(s.subtitle)}</div>
        ${tree.description ? `<p class="cover-desc">${escapeHtml(tree.description)}</p>` : ''}
        <div class="cover-meta">
          <span>${generationCount} ${escapeHtml(s.generations)}</span>
          <span class="dot">·</span>
          <span>${memberCount} ${escapeHtml(s.members)}</span>
          ${rangeLabel !== s.noData ? `<span class="dot">·</span><span>${escapeHtml(rangeLabel)}</span>` : ''}
        </div>
        <div class="cover-foot">${escapeHtml(s.generatedBy)} ${escapeHtml(s.on)} ${escapeHtml(today)}</div>
        <p class="footer-confidential">${escapeHtml(s.docFooterConfidential)}</p>
      </div>
    </section>`;

  // ---- Sommaire (page 2) ----------------------------------------------------
  const indexLinks = groups
    .map(({ gen, people }) => {
      const label =
        gen === 0
          ? `${s.generation} 1 — ${s.founders}`
          : `${s.generation} ${gen + 1}`;
      return `<li><span class="toc-gen">${escapeHtml(label)}</span><span class="toc-count">${people.length}</span></li>`;
    })
    .join('');

  const sommaire = `
    <section class="page sommaire">
      <h2 class="sect-title">${escapeHtml(s.sommaireTitle)}</h2>
      <div class="stats-row">
        <div class="stat"><span class="stat-val">${generationCount}</span><span class="stat-lbl">${escapeHtml(s.generations)}</span></div>
        <div class="stat"><span class="stat-val">${memberCount}</span><span class="stat-lbl">${escapeHtml(s.members)}</span></div>
        <div class="stat"><span class="stat-val">${escapeHtml(rangeLabel)}</span><span class="stat-lbl">${escapeHtml(s.fromTo)}</span></div>
      </div>
      <h3 class="toc-title">${escapeHtml(s.sommaire)}</h3>
      <ul class="toc">${indexLinks}</ul>
    </section>`;

  // ---- Generation sections (pages 3..N) -------------------------------------
  const genSections = groups
    .map(({ gen, people }) => {
      const bandLabel =
        gen === 0
          ? `${s.generation.toUpperCase()} 1 — ${s.founders.toUpperCase()}`
          : `${s.generation.toUpperCase()} ${gen + 1}`;

      const fiches = people
        .map((p) => fichePerson(p, tree, options, s, pal))
        .join('');

      return `
      <section class="page gen-page">
        <div class="gen-band">${escapeHtml(bandLabel)}</div>
        <div class="fiches">${fiches}</div>
      </section>`;
    })
    .join('');

  // ---- Index (last page) ----------------------------------------------------
  const memo = new Map<string, number>();
  const sortedAll = [...tree.persons].sort(
    (a, b) => a.lastName.localeCompare(b.lastName) || a.firstName.localeCompare(b.firstName),
  );
  const indexRows = sortedAll
    .map((p) => {
      const g = getGeneration(p.id, tree.relationships, tree.persons, memo) + 1;
      const by = p.birthDate ? formatYear(p.birthDate) : '';
      const dy = p.deathDate ? formatYear(p.deathDate) : '';
      const lifespan = by || dy ? `${by}${by || dy ? '–' : ''}${dy}` : '';
      return `<li><span class="ix-name"><strong>${escapeHtml(p.lastName)}</strong>, ${escapeHtml(p.firstName)}</span><span class="ix-meta">${escapeHtml(s.gen)} ${g}${lifespan ? ` · ${escapeHtml(lifespan)}` : ''}</span></li>`;
    })
    .join('');

  const index = `
    <section class="page index-page">
      <h2 class="sect-title">${escapeHtml(s.index)}</h2>
      <ul class="index-list">${indexRows}</ul>
    </section>`;

  const margin = pageMargin(options.paperSize);

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(s.family)} ${escapeHtml(tree.name)} | Suimini</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@500;600;700;800&family=Hanken+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    @page { size: ${options.paperSize}; margin: ${margin}; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { background: ${pal.bg}; color: ${pal.ink}; font-family: ${pal.body}; }
    body { font-size: 11pt; line-height: 1.5; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

    .page { background: ${pal.bg}; padding: 0; }
    .page + .page { page-break-before: always; }
    .cover, .sommaire, .gen-page, .index-page { page-break-after: always; }
    .index-page { page-break-after: auto; }

    /* ---- Cover ---- */
    .cover { min-height: 86vh; display: flex; align-items: center; justify-content: center; text-align: center; border-bottom: 6px solid ${pal.accent}; padding: 24pt; }
    .cover-inner { max-width: 80%; }
    .cover-eyebrow { font-family: ${pal.display}; text-transform: uppercase; letter-spacing: 5px; font-size: 10pt; color: ${pal.accent}; margin-bottom: 18pt; }
    .cover-title { font-family: ${pal.display}; font-weight: 800; font-size: 40pt; line-height: 1.04; color: ${pal.ink}; margin-bottom: 12pt; }
    .cover-sub { font-family: ${pal.display}; font-size: 14pt; color: ${pal.inkSoft}; margin-bottom: 16pt; }
    .cover-desc { font-size: 11pt; color: ${pal.inkSoft}; max-width: 80%; margin: 0 auto 18pt; }
    .cover-meta { font-family: ${pal.display}; font-size: 11pt; color: ${pal.ink}; display: flex; gap: 8pt; justify-content: center; align-items: center; margin-bottom: 26pt; }
    .cover-meta .dot { color: ${pal.accent}; }
    .cover-foot { font-size: 9pt; letter-spacing: 1px; color: ${pal.inkSoft}; text-transform: uppercase; }
    .footer-confidential { font-size: 8pt; font-style: italic; opacity: 0.5; text-align: center; color: ${pal.inkSoft}; margin: 4pt 0 0 0; }

    /* ---- Section titles ---- */
    .sect-title { font-family: ${pal.display}; font-weight: 700; font-size: 22pt; color: ${pal.ink}; border-bottom: 2px solid ${pal.separator}; padding-bottom: 8pt; margin-bottom: 18pt; }

    /* ---- Sommaire ---- */
    .stats-row { display: flex; gap: 18pt; margin-bottom: 24pt; }
    .stat { flex: 1; border: ${pal.ficheBorder}; ${pal.ficheShadow !== 'none' ? `box-shadow: ${pal.ficheShadow};` : ''} background: ${pal.cardBg}; padding: 14pt; text-align: center; }
    .stat-val { display: block; font-family: ${pal.display}; font-weight: 800; font-size: 24pt; color: ${pal.accent}; }
    .stat-lbl { display: block; font-size: 8pt; text-transform: uppercase; letter-spacing: 1px; color: ${pal.inkSoft}; margin-top: 4pt; }
    .toc-title { font-family: ${pal.display}; font-size: 13pt; color: ${pal.ink}; margin-bottom: 10pt; }
    .toc { list-style: none; }
    .toc li { display: flex; justify-content: space-between; align-items: baseline; padding: 7pt 0; border-bottom: 1px dotted ${pal.border}; }
    .toc-gen { font-family: ${pal.display}; font-size: 11pt; color: ${pal.ink}; }
    .toc-count { font-family: ${pal.display}; font-weight: 700; color: ${pal.accent}; }

    /* ---- Generation pages ---- */
    .gen-band { background: ${pal.bandBg}; color: ${pal.bandInk}; font-family: ${pal.display}; font-weight: 700; font-size: 14pt; letter-spacing: 2px; text-transform: uppercase; padding: 10pt 14pt; margin-bottom: 16pt; ${options.theme === 'minimal' ? `border-bottom: 2px solid ${pal.ink}; padding-left: 0; padding-right: 0;` : `border: ${pal.ficheBorder};`} }
    .fiches { display: flex; flex-direction: column; gap: 14pt; }
    .fiche { background: ${pal.cardBg}; border: ${pal.ficheBorder}; ${pal.ficheShadow !== 'none' ? `box-shadow: ${pal.ficheShadow};` : ''} padding: 12pt 14pt; page-break-inside: avoid; border-left: 4px solid ${pal.accent}; }
    .fiche-head { display: flex; gap: 12pt; align-items: flex-start; }
    .fiche-photo { width: 80px; height: 80px; flex-shrink: 0; object-fit: cover; border: ${pal.ficheBorder}; background: ${pal.bg}; }
    .fiche-main { flex: 1; min-width: 0; }
    .fiche-name { font-family: ${pal.display}; font-weight: 700; font-size: 14pt; color: ${pal.ink}; }
    .fiche-line { font-size: 10pt; color: ${pal.inkSoft}; margin-top: 3pt; }
    .fiche-occ { font-size: 10pt; color: ${pal.ink}; margin-top: 3pt; }
    .fiche-occ .lbl { font-family: ${pal.display}; text-transform: uppercase; font-size: 8pt; letter-spacing: 1px; color: ${pal.inkSoft}; margin-right: 4pt; }
    .fiche-bio { margin-top: 8pt; padding-top: 8pt; border-top: 1px solid ${pal.border}; font-size: 9.5pt; color: ${pal.inkSoft}; font-style: italic; }
    .fiche-bio .lbl { display: block; font-family: ${pal.display}; font-style: normal; text-transform: uppercase; font-size: 8pt; letter-spacing: 1px; color: ${pal.ink}; margin-bottom: 3pt; }
    .fiche-rels { margin-top: 8pt; font-size: 9.5pt; color: ${pal.inkSoft}; }
    .fiche-rels div { margin-top: 2pt; }
    .fiche-rels .lbl { font-family: ${pal.display}; font-weight: 700; color: ${pal.ink}; }
    .fiche-chrono { margin-top: 6pt; font-size: 9pt; color: ${pal.inkSoft}; }
    .fiche-chrono .lbl { font-family: ${pal.display}; font-weight: 700; color: ${pal.ink}; margin-right: 4pt; }
    .dagger { color: ${pal.accent}; }

    /* ---- Index ---- */
    .index-list { list-style: none; column-count: 2; column-gap: 24pt; }
    .index-list li { break-inside: avoid; display: flex; justify-content: space-between; align-items: baseline; gap: 8pt; padding: 4pt 0; border-bottom: 1px solid ${pal.border}; font-size: 9.5pt; }
    .ix-meta { color: ${pal.inkSoft}; font-family: ${pal.display}; font-size: 8pt; white-space: nowrap; }
  </style>
</head>
<body>
${cover}
${sommaire}
${genSections}
${index}
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Per-person fiche
// ---------------------------------------------------------------------------

function fichePerson(
  p: Person,
  tree: FamilyTree,
  options: ExportOptions,
  s: Strings,
  pal: Palette,
): string {
  const { relationships, persons } = tree;
  const parents = getParents(p.id, relationships, persons);
  const spouses = getSpouses(p.id, relationships, persons);
  const children = getChildren(p.id, relationships, persons);

  // NB: this <img> lives inside an HTML string (not JSX), so the Next no-img-element
  // rule does not apply — the booklet is rendered by the browser print window.
  const photo =
    options.includePhotos && p.profilePhoto
      ? `<img class="fiche-photo" src="${escapeHtml(p.profilePhoto)}" alt="">`
      : '';

  // Birth line
  let birthLine = '';
  if (p.birthDate || p.birthPlace?.city) {
    const dateTxt = p.birthDate ? `${bornLabel(p, s)} ${escapeHtml(formatDate(p.birthDate, p.birthDateApprox))}` : '';
    const placeTxt = p.birthPlace?.city ? ` ${s.in} ${escapeHtml(place(p.birthPlace))}` : '';
    birthLine = `<div class="fiche-line">${dateTxt}${placeTxt}</div>`;
  }

  // Death line
  let deathLine = '';
  if (!p.isAlive && (p.deathDate || p.deathPlace?.city)) {
    const dateTxt = p.deathDate ? `${diedLabel(p, s)} ${escapeHtml(formatDate(p.deathDate, p.deathDateApprox))}` : diedLabel(p, s);
    const placeTxt = p.deathPlace?.city ? ` ${s.in} ${escapeHtml(place(p.deathPlace))}` : '';
    deathLine = `<div class="fiche-line"><span class="dagger">&dagger;</span> ${dateTxt}${placeTxt}</div>`;
  }

  const occ = p.occupation
    ? `<div class="fiche-occ"><span class="lbl">${escapeHtml(s.occupation)}</span>${escapeHtml(p.occupation)}</div>`
    : '';

  const bio =
    options.includeBios && p.bio && p.bio.trim()
      ? `<div class="fiche-bio"><span class="lbl">${escapeHtml(s.biography)}</span>${escapeHtml(p.bio)}</div>`
      : '';

  const relLine = (label: string, people: Person[]): string => {
    if (people.length === 0) return '';
    const names = people.map((x) => escapeHtml(getDisplayName(x))).join(', ');
    return `<div><span class="lbl">${escapeHtml(label)} :</span> ${names}</div>`;
  };
  const relsInner = [
    relLine(s.parents, parents),
    relLine(s.spouses, spouses),
    relLine(s.children, children),
  ].join('');
  const rels = relsInner ? `<div class="fiche-rels">${relsInner}</div>` : '';

  let chrono = '';
  if (options.includeTimeline && p.events && p.events.length > 0) {
    const items = p.events
      .map((e) => {
        const y = e.date ? formatYear(e.date) : '';
        return escapeHtml(`${e.type}${y ? ` (${y})` : ''}`);
      })
      .join(' · ');
    if (items) {
      chrono = `<div class="fiche-chrono"><span class="lbl">${escapeHtml(s.chronology)} :</span>${items}</div>`;
    }
  }

  const dagger = !p.isAlive ? ' <span class="dagger">&dagger;</span>' : '';

  return `
    <div class="fiche">
      <div class="fiche-head">
        ${photo}
        <div class="fiche-main">
          <div class="fiche-name">${escapeHtml(getDisplayName(p).toUpperCase())}${dagger}</div>
          ${birthLine}
          ${deathLine}
          ${occ}
        </div>
      </div>
      ${bio}
      ${rels}
      ${chrono}
    </div>`;
}
