import { test, expect } from '@playwright/test';
import { memberJoinedEmailHtml } from '@/lib/emails';

/**
 * Screenshot capture for the PDF-booklet + owner-notification-email features.
 * See feature-screenshots.spec.ts for why these now run in CI instead of
 * being permanently local-only: every wait is a real `expect(...)`, and the
 * email test no longer depends on a hand-placed `/tmp/*.html` fixture (that
 * file was never generated by anything in the repo, so this test was
 * guaranteed to fail on a fresh CI runner as-is — it now renders the real
 * template in-memory via `page.setContent`).
 */

test('shot: export PDF modal + generated booklet', async ({ page, context }) => {
  // Neutralise window.print() so the popup never blocks on a print dialog.
  await context.addInitScript(() => { window.print = () => {}; });

  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto('/');
  const demoBtn = page.getByRole('button', { name: /Essayer la démo/i }).first();
  await expect(demoBtn).toBeVisible();
  await Promise.all([page.waitForURL('**/app'), demoBtn.click()]);
  // Same fix as dashboard-screenshot.spec.ts / feature-screenshots.spec.ts:
  // the demo tree always exists, so the <h1> shows its name, never "Bonjour".
  await expect(page.getByRole('heading', { name: 'Famille Dupont' })).toBeVisible({ timeout: 15_000 });

  // Open the export modal via the sidebar "Exporter le livret" button.
  const exportBtn = page.getByRole('button', { name: /Exporter le livret/i }).first();
  await expect(exportBtn).toBeVisible({ timeout: 8_000 });
  await exportBtn.click();
  await page.waitForTimeout(600); // modal open transition
  await page.screenshot({ path: 'shot-pdf-modal.png' });

  // Generate → the booklet HTML opens in a popup window.
  const popupPromise = context.waitForEvent('page', { timeout: 15_000 });
  const genBtn = page.getByRole('button', { name: /Générer le PDF/i }).first();
  await genBtn.click();
  const popup = await popupPromise;
  await popup.waitForLoadState('domcontentloaded');
  await popup.waitForTimeout(1500); // let Google Fonts + layout settle
  await popup.screenshot({ path: 'shot-pdf-booklet.png', fullPage: true });
});

test('shot: owner notification email', async ({ page }) => {
  await page.setViewportSize({ width: 760, height: 900 });
  const html = memberJoinedEmailHtml({
    ownerName: 'Nelson',
    memberName: 'Amina Djoumessi',
    treeName: 'Famille Djoumessi',
    treeUrl: 'https://suimini.vercel.app/app',
  });
  await page.setContent(html);
  await expect(page.locator('body')).toBeVisible();
  await page.screenshot({ path: 'shot-email-notification.png', fullPage: true });
});
