import type { Metadata, Viewport } from "next";
import { Spectral, Plus_Jakarta_Sans, IBM_Plex_Mono } from "next/font/google";
import IntlProvider from "@/components/IntlProvider";
import { getLocale } from "next-intl/server";
import { isLocale, DEFAULT_LOCALE } from "@/i18n/config";
import "./globals.css";

// Modern Heritage type system — self-hosted via next/font (no FOUT, no render-blocking @import).
// Display = Spectral (titles, names, key numbers — matches the constellation landing),
// Body/UI/labels = Plus Jakarta Sans (high-readability humanist sans with character),
// Mono = IBM Plex Mono (dates, labels, IDs).
const display = Spectral({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"], style: ["normal", "italic"], variable: "--font-display", display: "swap" });
const body = Plus_Jakarta_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"], style: ["normal", "italic"], variable: "--font-body", display: "swap" });
const mono = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400", "500", "700"], variable: "--font-mono", display: "swap" });

const SITE_URL = "https://suimini.vercel.app";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Suimini | Arbre Généalogique",
  description:
    "Préservez l'histoire de votre famille, génération après génération. Créez votre arbre généalogique en ligne, collaboratif et élégant.",
  keywords: "arbre généalogique, généalogie, famille, ancêtres, histoire familiale, GEDCOM",
  authors: [{ name: "Suimini" }],
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Suimini",
  },
  icons: {
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
      { url: "/icon-192.svg", sizes: "192x192", type: "image/svg+xml" },
    ],
    apple: [{ url: "/icon-192.png", sizes: "192x192", type: "image/png" }],
  },
  openGraph: {
    title: "Suimini | Arbre Généalogique",
    description: "Préservez l'histoire de votre famille",
    url: SITE_URL,
    siteName: "Suimini",
    images: [{ url: `${SITE_URL}/og.png`, width: 1200, height: 630, alt: "Suimini, arbre généalogique" }],
    locale: "fr_FR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Suimini | Arbre Généalogique",
    description: "Préservez l'histoire de votre famille",
    images: [`${SITE_URL}/og.png`],
  },
  robots: { index: true, follow: true },
  alternates: { canonical: SITE_URL },
};

export const viewport: Viewport = {
  themeColor: "#111118",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

// Origin of the Supabase project (auth + data), preconnected for faster first call.
const SUPABASE_ORIGIN = (() => {
  try { return process.env.NEXT_PUBLIC_SUPABASE_URL ? new URL(process.env.NEXT_PUBLIC_SUPABASE_URL).origin : null; }
  catch { return null; }
})();

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Locale is seeded from the cookie (no URL routing) for SSR + first paint; the
  // client IntlProvider then switches it in real time without a reload.
  const cookieLocale = await getLocale();
  const locale = isLocale(cookieLocale) ? cookieLocale : DEFAULT_LOCALE;
  return (
    <html lang={locale} data-theme="dark" style={{ colorScheme: "dark" }} className={`${display.variable} ${body.variable} ${mono.variable}`}>
      <head>
        {/* next/font self-hosts the fonts, so we only hint at the runtime origins we actually hit. */}
        {SUPABASE_ORIGIN && <link rel="preconnect" href={SUPABASE_ORIGIN} crossOrigin="anonymous" />}
        {SUPABASE_ORIGIN && <link rel="dns-prefetch" href={SUPABASE_ORIGIN} />}
        {/* Avatar/illustration CDN used on the landing & sample data. */}
        <link rel="dns-prefetch" href="https://api.dicebear.com" />
        {/* iOS splash screens — sized per device. Generated by scripts/generate-splash.mjs. */}
        <link rel="apple-touch-startup-image" href="/splash-1170x2532.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/splash-1290x2796.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/splash-1179x2556.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/splash-1284x2778.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/splash-1125x2436.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/splash-828x1792.png"  media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" />
        <link rel="apple-touch-startup-image" href="/splash-750x1334.png"  media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" />
        <link rel="apple-touch-startup-image" href="/splash-640x1136.png"  media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" />
      </head>
      <body>
        <IntlProvider initialLocale={locale}>
          {children}
        </IntlProvider>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function () {
                  navigator.serviceWorker.register('/sw.js').catch(function (err) {
                    console.error('SW registration failed:', err);
                  });
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
