import { FamilyTree, Person, Relationship } from './types';

export const samplePersons: Person[] = [
  {
    id: 'p1',
    firstName: 'Henri',
    lastName: 'Dupont',
    gender: 'male',
    birthDate: '1935-04-12',
    birthPlace: { city: 'Lyon', country: 'France' },
    deathDate: '2010-11-03',
    deathPlace: { city: 'Paris', country: 'France' },
    isAlive: false,
    occupation: 'Ingénieur',
    bio: 'Fondateur de la famille Dupont, Henri était un ingénieur talentueux ayant travaillé pour plusieurs grandes entreprises françaises.',
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Henri',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['fondateur', 'ingénieur'],
    dnaOrigins: [
      { region: "Europe de l'Ouest", percent: 55 },
      { region: 'Afrique subsaharienne', percent: 30 },
      { region: "Asie de l'Est", percent: 15 },
    ],
    events: [
      { id: 'e1', type: 'birth', date: '1935-04-12', place: { city: 'Lyon', country: 'France' } },
      { id: 'e2', type: 'marriage', date: '1960-06-15', place: { city: 'Paris', country: 'France' } },
      { id: 'e3', type: 'death', date: '2010-11-03', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p2',
    firstName: 'Marguerite',
    lastName: 'Dupont',
    maidenName: 'Martin',
    gender: 'female',
    birthDate: '1938-08-22',
    birthPlace: { city: 'Bordeaux', country: 'France' },
    deathDate: '2018-03-15',
    deathPlace: { city: 'Paris', country: 'France' },
    isAlive: false,
    occupation: 'Institutrice',
    bio: 'Marguerite était une institutrice dévouée qui a élevé trois enfants avec amour et sagesse.',
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Marguerite',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['enseignante'],
    events: [
      { id: 'e4', type: 'birth', date: '1938-08-22', place: { city: 'Bordeaux', country: 'France' } },
      { id: 'e5', type: 'marriage', date: '1960-06-15', place: { city: 'Paris', country: 'France' } },
      { id: 'e6', type: 'death', date: '2018-03-15', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p3',
    firstName: 'Pierre',
    lastName: 'Dupont',
    gender: 'male',
    birthDate: '1962-02-14',
    birthPlace: { city: 'Paris', country: 'France' },
    isAlive: true,
    occupation: 'Médecin',
    bio: 'Pierre est médecin généraliste à Toulouse depuis 1990.',
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Pierre',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['médecin'],
    events: [
      { id: 'e7', type: 'birth', date: '1962-02-14', place: { city: 'Paris', country: 'France' } },
      { id: 'e8', type: 'marriage', date: '1990-07-20', place: { city: 'Toulouse', country: 'France' } },
      { id: 'e9', type: 'graduation', date: '1988-06-01', description: 'Diplôme de médecine' },
    ],
  },
  {
    id: 'p4',
    firstName: 'Isabelle',
    lastName: 'Dupont',
    maidenName: 'Bernard',
    gender: 'female',
    birthDate: '1965-09-30',
    birthPlace: { city: 'Toulouse', country: 'France' },
    isAlive: true,
    occupation: 'Architecte',
    bio: "Isabelle est architecte renommée, spécialisée dans l'architecture bioclimatique.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Isabelle',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e10', type: 'birth', date: '1965-09-30', place: { city: 'Toulouse', country: 'France' } },
      { id: 'e11', type: 'marriage', date: '1990-07-20', place: { city: 'Toulouse', country: 'France' } },
    ],
  },
  {
    id: 'p5',
    firstName: 'Sophie',
    lastName: 'Dupont',
    gender: 'female',
    birthDate: '1964-11-05',
    birthPlace: { city: 'Paris', country: 'France' },
    isAlive: true,
    occupation: 'Journaliste',
    bio: 'Sophie travaille pour un grand journal parisien depuis 1990.',
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Sophie',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e12', type: 'birth', date: '1964-11-05', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p6',
    firstName: 'Thomas',
    lastName: 'Dupont',
    gender: 'male',
    birthDate: '1968-07-19',
    birthPlace: { city: 'Paris', country: 'France' },
    isAlive: true,
    occupation: 'Chef cuisinier',
    bio: 'Thomas est chef étoilé au guide Michelin, propriétaire du restaurant "Le Dupont" à Paris.',
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Thomas',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['chef', 'étoilé'],
    events: [
      { id: 'e13', type: 'birth', date: '1968-07-19', place: { city: 'Paris', country: 'France' } },
      { id: 'e14', type: 'marriage', date: '1995-05-10', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p7',
    firstName: 'Claire',
    lastName: 'Dupont',
    maidenName: 'Lefebvre',
    gender: 'female',
    birthDate: '1970-03-25',
    birthPlace: { city: 'Marseille', country: 'France' },
    isAlive: true,
    occupation: 'Photographe',
    bio: "Claire est photographe artistique reconnue internationalement pour ses portraits de famille.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Claire',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e15', type: 'birth', date: '1970-03-25', place: { city: 'Marseille', country: 'France' } },
      { id: 'e16', type: 'marriage', date: '1995-05-10', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p8',
    firstName: 'Lucas',
    lastName: 'Dupont',
    gender: 'male',
    birthDate: '1992-01-08',
    birthPlace: { city: 'Toulouse', country: 'France' },
    isAlive: true,
    occupation: 'Développeur',
    bio: "Lucas est développeur web freelance. C'est lui qui maintient l'arbre de la famille à jour.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Lucas',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e17', type: 'birth', date: '1992-01-08', place: { city: 'Toulouse', country: 'France' } },
    ],
  },
  {
    id: 'p9',
    firstName: 'Emma',
    lastName: 'Dupont',
    gender: 'female',
    birthDate: '1995-06-17',
    birthPlace: { city: 'Toulouse', country: 'France' },
    isAlive: true,
    occupation: 'Étudiante',
    bio: "Emma termine ses études d'ingénieure agronome à Toulouse, dans la lignée agricole de ses aïeux.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Emma',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e18', type: 'birth', date: '1995-06-17', place: { city: 'Toulouse', country: 'France' } },
    ],
  },
  {
    id: 'p10',
    firstName: 'Hugo',
    lastName: 'Dupont',
    gender: 'male',
    birthDate: '1997-10-22',
    birthPlace: { city: 'Paris', country: 'France' },
    isAlive: true,
    occupation: 'Musicien',
    bio: "Hugo est musicien : il joue du violoncelle dans un orchestre de chambre parisien.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Hugo',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e19', type: 'birth', date: '1997-10-22', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p11',
    firstName: 'Léa',
    lastName: 'Dupont',
    gender: 'female',
    birthDate: '2000-04-03',
    birthPlace: { city: 'Paris', country: 'France' },
    isAlive: true,
    occupation: 'Lycéenne',
    bio: "Léa, la cadette de la branche parisienne, prépare le concours d'entrée d'une école d'art.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Lea',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e20', type: 'birth', date: '2000-04-03', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p12',
    firstName: 'Marie',
    lastName: 'Leroux',
    maidenName: 'Petit',
    gender: 'female',
    birthDate: '1910-03-18',
    birthPlace: { city: 'Bordeaux', country: 'France' },
    deathDate: '1985-09-05',
    deathPlace: { city: 'Bordeaux', country: 'France' },
    isAlive: false,
    occupation: 'Couturière',
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Marie',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e21', type: 'birth', date: '1910-03-18', place: { city: 'Bordeaux', country: 'France' } },
    ],
  },
  {
    id: 'p13',
    firstName: 'André',
    lastName: 'Martin',
    gender: 'male',
    birthDate: '1905-12-25',
    birthPlace: { city: 'Lyon', country: 'France' },
    deathDate: '1980-07-14',
    deathPlace: { city: 'Bordeaux', country: 'France' },
    isAlive: false,
    occupation: 'Agriculteur',
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Andre',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e22', type: 'birth', date: '1905-12-25', place: { city: 'Lyon', country: 'France' } },
    ],
  },
  {
    id: 'p14',
    firstName: 'Jules',
    lastName: 'Dupont',
    gender: 'male',
    birthDate: '1906-05-09',
    birthPlace: { city: 'Lyon', country: 'France' },
    deathDate: '1985-02-28',
    deathPlace: { city: 'Lyon', country: 'France' },
    isAlive: false,
    occupation: 'Menuisier',
    bio: "Patriarche de la lignée, Jules tenait un atelier de menuiserie réputé dans le Vieux Lyon. Il a transmis le goût du travail bien fait à toute sa descendance.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Jules',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['patriarche', 'artisan'],
    events: [
      { id: 'e23', type: 'birth', date: '1906-05-09', place: { city: 'Lyon', country: 'France' } },
      { id: 'e24', type: 'marriage', date: '1932-09-03', place: { city: 'Lyon', country: 'France' } },
    ],
  },
  {
    id: 'p15',
    firstName: 'Augustine',
    lastName: 'Dupont',
    maidenName: 'Roche',
    gender: 'female',
    birthDate: '1910-11-14',
    birthPlace: { city: 'Grenoble', country: 'France' },
    deathDate: '1992-12-01',
    deathPlace: { city: 'Lyon', country: 'France' },
    isAlive: false,
    occupation: 'Couturière',
    bio: "Augustine cousait pour les grandes maisons lyonnaises de la soie. Femme de caractère, elle a tenu la maison familiale pendant la guerre.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Augustine',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e25', type: 'birth', date: '1910-11-14', place: { city: 'Grenoble', country: 'France' } },
    ],
  },
  {
    id: 'p16',
    firstName: 'Bernard',
    lastName: 'Moreau',
    gender: 'male',
    birthDate: '1961-04-02',
    birthPlace: { city: 'Lyon', country: 'France' },
    isAlive: true,
    occupation: 'Professeur',
    bio: "Bernard enseigne l'histoire-géographie au lycée depuis trente ans. Passionné de généalogie, c'est lui qui a lancé la reconstitution de l'arbre familial.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Bernard',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['enseignant'],
    events: [
      { id: 'e26', type: 'birth', date: '1961-04-02', place: { city: 'Lyon', country: 'France' } },
      { id: 'e27', type: 'marriage', date: '1989-08-26', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p17',
    firstName: 'Camille',
    lastName: 'Moreau',
    gender: 'female',
    birthDate: '1991-12-11',
    birthPlace: { city: 'Paris', country: 'France' },
    isAlive: true,
    occupation: 'Vétérinaire',
    bio: "Camille a ouvert sa clinique vétérinaire à Nantes. Elle partage les photos de la ferme familiale sur le journal de l'arbre.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Camille',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e28', type: 'birth', date: '1991-12-11', place: { city: 'Paris', country: 'France' } },
    ],
  },
  {
    id: 'p18',
    firstName: 'Nathalie',
    lastName: 'Dupont',
    maidenName: 'Fontaine',
    gender: 'female',
    birthDate: '1993-03-29',
    birthPlace: { city: 'Toulouse', country: 'France' },
    isAlive: true,
    occupation: 'Infirmière',
    bio: "Nathalie est infirmière en pédiatrie au CHU de Toulouse. Elle a épousé Lucas en 2017.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Nathalie',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    events: [
      { id: 'e29', type: 'birth', date: '1993-03-29', place: { city: 'Toulouse', country: 'France' } },
      { id: 'e30', type: 'marriage', date: '2017-06-24', place: { city: 'Toulouse', country: 'France' } },
    ],
  },
  {
    id: 'p19',
    firstName: 'Gabriel',
    lastName: 'Dupont',
    gender: 'male',
    birthDate: '2019-09-12',
    birthPlace: { city: 'Toulouse', country: 'France' },
    isAlive: true,
    bio: "Benjamin de la famille, Gabriel représente la cinquième génération recensée dans l'arbre.",
    profilePhoto: 'https://api.dicebear.com/7.x/personas/svg?seed=Gabriel',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['benjamin'],
    events: [
      { id: 'e31', type: 'birth', date: '2019-09-12', place: { city: 'Toulouse', country: 'France' } },
    ],
  },
];

export const sampleRelationships: Relationship[] = [
  // Henri + Marguerite married
  { id: 'r1', type: 'spouse', person1Id: 'p1', person2Id: 'p2', startDate: '1960-06-15', isActive: false },
  // Henri parent of Pierre, Sophie, Thomas
  { id: 'r2', type: 'parent', person1Id: 'p1', person2Id: 'p3' },
  { id: 'r3', type: 'parent', person1Id: 'p1', person2Id: 'p5' },
  { id: 'r4', type: 'parent', person1Id: 'p1', person2Id: 'p6' },
  // Marguerite parent of Pierre, Sophie, Thomas
  { id: 'r5', type: 'parent', person1Id: 'p2', person2Id: 'p3' },
  { id: 'r6', type: 'parent', person1Id: 'p2', person2Id: 'p5' },
  { id: 'r7', type: 'parent', person1Id: 'p2', person2Id: 'p6' },
  // Pierre + Isabelle married
  { id: 'r8', type: 'spouse', person1Id: 'p3', person2Id: 'p4', startDate: '1990-07-20', isActive: true },
  // Thomas + Claire married
  { id: 'r9', type: 'spouse', person1Id: 'p6', person2Id: 'p7', startDate: '1995-05-10', isActive: true },
  // Pierre parent of Lucas, Emma
  { id: 'r10', type: 'parent', person1Id: 'p3', person2Id: 'p8' },
  { id: 'r11', type: 'parent', person1Id: 'p3', person2Id: 'p9' },
  // Isabelle parent of Lucas, Emma
  { id: 'r12', type: 'parent', person1Id: 'p4', person2Id: 'p8' },
  { id: 'r13', type: 'parent', person1Id: 'p4', person2Id: 'p9' },
  // Thomas parent of Hugo, Léa
  { id: 'r14', type: 'parent', person1Id: 'p6', person2Id: 'p10' },
  { id: 'r15', type: 'parent', person1Id: 'p6', person2Id: 'p11' },
  // Claire parent of Hugo, Léa
  { id: 'r16', type: 'parent', person1Id: 'p7', person2Id: 'p10' },
  { id: 'r17', type: 'parent', person1Id: 'p7', person2Id: 'p11' },
  // Marguerite's parents
  { id: 'r18', type: 'parent', person1Id: 'p12', person2Id: 'p2' },
  { id: 'r19', type: 'parent', person1Id: 'p13', person2Id: 'p2' },
  { id: 'r20', type: 'spouse', person1Id: 'p12', person2Id: 'p13', startDate: '1933-05-01', isActive: false },
  // Jules + Augustine (great-grandparents), parents of Henri
  { id: 'r21', type: 'spouse', person1Id: 'p14', person2Id: 'p15', startDate: '1932-09-03', isActive: false },
  { id: 'r22', type: 'parent', person1Id: 'p14', person2Id: 'p1' },
  { id: 'r23', type: 'parent', person1Id: 'p15', person2Id: 'p1' },
  // Sophie + Bernard, parents of Camille
  { id: 'r24', type: 'spouse', person1Id: 'p5', person2Id: 'p16', startDate: '1989-08-26', isActive: true },
  { id: 'r25', type: 'parent', person1Id: 'p5', person2Id: 'p17' },
  { id: 'r26', type: 'parent', person1Id: 'p16', person2Id: 'p17' },
  // Lucas + Nathalie, parents of Gabriel (5th generation)
  { id: 'r27', type: 'spouse', person1Id: 'p8', person2Id: 'p18', startDate: '2017-06-24', isActive: true },
  { id: 'r28', type: 'parent', person1Id: 'p8', person2Id: 'p19' },
  { id: 'r29', type: 'parent', person1Id: 'p18', person2Id: 'p19' },
];

export const sampleFamilyTree: FamilyTree = {
  id: 'tree1',
  name: 'Famille Dupont',
  description: "L'arbre généalogique de la famille Dupont — 5 générations, de 1906 à aujourd'hui. Données fictives de démonstration.",
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-06-01T00:00:00Z',
  persons: samplePersons,
  relationships: sampleRelationships,
  journal: [
    {
      id: 'j1',
      title: 'Réunion de famille à Paris',
      date: '2023-07-15',
      content: "Toute la famille s'est réunie dans la maison familiale. Henri nous a raconté ses souvenirs d'enfance à Lyon, et nous avons feuilleté les vieux albums photos ensemble.",
      mentionedPersonIds: ['p1', 'p3', 'p6'],
      createdAt: '2023-07-16T00:00:00Z',
      updatedAt: '2023-07-16T00:00:00Z',
    },
  ],
  rootPersonId: 'p1',
  settings: {
    defaultView: 'tree',
    showPhotos: true,
    showDates: true,
    showPlaces: true,
    colorScheme: 'default',
    generationsToShow: 6,
  },
};
